Repository glotzerlab/coxeter, pull requests merged in 2020-10, with the labels that each got.

#94 Document the call operator for shape families.
  doc/source/package-shape-families.rst
Labels: documentation

#95 Improve golden ratio documentation
  coxeter/shape_families/plane_shape_families.py
Labels: documentation, enhancement

#96 Fix package naming of euclid/coxeter and typo in Bentley-Ottmann.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  coxeter/bentley_ottmann/LICENSE
  coxeter/bentley_ottmann/__init__.py
  coxeter/bentley_ottmann/poly_point_isect.py
  coxeter/shape_classes/polygon.py
  doc/source/development.rst
  setup.cfg
Labels: bug, documentation

#99 Refactor/modify families api
  ChangeLog.rst
  coxeter/shape_families/common_families.py
  coxeter/shape_families/doi_data_repositories.py
  coxeter/shape_families/plane_shape_families.py
  coxeter/shape_families/shape_family.py
  coxeter/shape_families/tabulated_shape_family.py
  doc/source/package-shape-families.rst
  tests/test_ft.py
  tests/test_polyhedron.py
  tests/test_shape_families.py
Labels: enhancement, refactor

#100 Assorted minor fixes
  ChangeLog.rst
  Credits.rst
  coxeter/__init__.py
  coxeter/shape_classes/__init__.py
  coxeter/shape_classes/circle.py
  coxeter/shape_classes/convex_polygon.py
  coxeter/shape_classes/convex_polyhedron.py
  coxeter/shape_classes/convex_spheropolygon.py
  coxeter/shape_classes/convex_spheropolyhedron.py
  coxeter/shape_classes/ellipse.py
  coxeter/shape_classes/ellipsoid.py
  coxeter/shape_classes/polygon.py
  coxeter/shape_classes/polyhedron.py
  coxeter/shape_classes/sphere.py
  coxeter/shape_families/common_families.py
  coxeter/shape_getters.py
  doc/source/conf.py
Labels: documentation

#106 Feature/expose doi data
  ChangeLog.rst
  coxeter/shape_families/__init__.py
  coxeter/shape_families/doi_data_repositories.py
  coxeter/shape_families/shape_family.py
  tests/test_polyhedron.py
  tests/test_shape_families.py
Labels: enhancement, refactor

#107 Feature/more abstract methods
  ChangeLog.rst
  coxeter/shape_classes/base_classes.py
  coxeter/shape_classes/circle.py
  coxeter/shape_classes/convex_spheropolygon.py
  coxeter/shape_classes/ellipse.py
  coxeter/shape_classes/ellipsoid.py
  coxeter/shape_classes/polygon.py
  coxeter/shape_classes/polyhedron.py
  tests/test_polygon.py
  tests/test_spheropolygon.py
Labels: enhancement

#109 Enable doctests
  .circleci/config.yml
  ChangeLog.rst
  Credits.rst
  coxeter/__doctest_fixtures.py
  coxeter/shape_classes/circle.py
  coxeter/shape_classes/convex_polygon.py
  coxeter/shape_classes/convex_polyhedron.py
  coxeter/shape_classes/convex_spheropolygon.py
  coxeter/shape_classes/convex_spheropolyhedron.py
  coxeter/shape_classes/ellipse.py
  coxeter/shape_classes/ellipsoid.py
  coxeter/shape_classes/polygon.py
  coxeter/shape_classes/polyhedron.py
  coxeter/shape_classes/sphere.py
  coxeter/shape_families/common_families.py
  setup.cfg
  tests/test_polyhedron.py
Labels: documentation, enhancement

#92 Feature/form factors
  ChangeLog.rst
  Credits.rst
  coxeter/__init__.py
  coxeter/ft.py
  coxeter/shape_classes/base_classes.py
  coxeter/shape_classes/polygon.py
  coxeter/shape_classes/polyhedron.py
  coxeter/shape_classes/sphere.py
  doc/source/coxeter.rst
  doc/source/module-ft.rst
  tests/test_ft.py
  tests/test_polygon.py
  tests/test_polyhedron.py
  tests/test_sphere.py
Labels: enhancement, refactor

#115 Refactor/rename subpackages
  ChangeLog.rst
  MANIFEST.in
  coxeter/__init__.py
  coxeter/families/__init__.py
  coxeter/families/common.py
  coxeter/families/data/MathematicaToPython.py
  coxeter/families/data/platonic.json
  coxeter/families/data/science1220869.json
  coxeter/families/doi_data_repositories.py
  coxeter/families/plane_shape_families.py
  coxeter/families/shape_family.py
  coxeter/families/tabulated_shape_family.py
  coxeter/shape_getters.py
  coxeter/shapes/__init__.py
  coxeter/shapes/base_classes.py
  coxeter/shapes/circle.py
  coxeter/shapes/convex_polygon.py
  coxeter/shapes/convex_polyhedron.py
  coxeter/shapes/convex_spheropolygon.py
  coxeter/shapes/convex_spheropolyhedron.py
  coxeter/shapes/ellipse.py
  coxeter/shapes/ellipsoid.py
  coxeter/shapes/polygon.py
  coxeter/shapes/polyhedron.py
  coxeter/shapes/sphere.py
  coxeter/shapes/utils.py
  doc/source/coxeter.rst
  doc/source/package-families.rst
  doc/source/package-shapes.rst
  setup.py
  tests/conftest.py
  tests/test_circle.py
  tests/test_ellipse.py
  tests/test_ellipsoid.py
  tests/test_polygon.py
  tests/test_polyhedron.py
  tests/test_shape_families.py
  tests/test_sphere.py
  tests/test_spheropolygon.py
  tests/utils.py
Labels: refactor

#119 Spheropolygon area setter
  ChangeLog.rst
  Credits.rst
  coxeter/families/shape_family.py
  coxeter/shapes/convex_spheropolygon.py
  tests/test_spheropolygon.py
Labels: enhancement

#121 Create axes for plotting if not provided.
  ChangeLog.rst
  Credits.rst
  coxeter/shapes/base_classes.py
  coxeter/shapes/polygon.py
  coxeter/shapes/polyhedron.py
  coxeter/shapes/utils.py
Labels: enhancement

#120 Fix test names
  tests/test_ellipse.py
  tests/test_ellipsoid.py
  tests/test_spheropolygon.py
Labels: bug

#123 Make a Python 3 wheel, not a universal wheel.
  setup.cfg
Labels: bug

#124 More consistent setters
  ChangeLog.rst
  Credits.rst
  coxeter/shapes/circle.py
  coxeter/shapes/convex_spheropolygon.py
  coxeter/shapes/convex_spheropolyhedron.py
  coxeter/shapes/ellipse.py
  coxeter/shapes/ellipsoid.py
  coxeter/shapes/polygon.py
  coxeter/shapes/polyhedron.py
  coxeter/shapes/sphere.py
  tests/test_ellipse.py
  tests/test_ellipsoid.py
Labels: enhancement

#127 Documentation revisions
  coxeter/shapes/circle.py
  coxeter/shapes/convex_spheropolygon.py
  coxeter/shapes/ellipse.py
  coxeter/shapes/ellipsoid.py
  coxeter/shapes/polygon.py
  coxeter/shapes/polyhedron.py
  coxeter/shapes/sphere.py
  coxeter/shapes/utils.py
Labels: documentation
